show databases;

create database customer_behaviour;

use customer_behaviour;

show tables

select * from customer;

#1.what is the total revenue generated by male vs female customers.

select gender,sum(purchase_amount)as revenue
from customer
group by gender;

#2.which customer used a discount but still spend more than the average purchase amount.

select
customer_id,
purchase_amount
from customer
where discount_applied="Yes" and purchase_amount>=(select AVG(purchase_amount) from customer)

select * from customer

#3.which are the top 5 products with highets average review rating.
select
item_purchased,
round(avg(review_rating),2) as product_average_ratings
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#4.compare the average purchased amount between standard and express shipping.
select
shipping_type,
round(avg(purchase_amount),2) as avg_purchased_amount
from  customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg_purchased_amount desc

#5.Do subsribed customers spend more?.compare average spend and total revenue between subscribers and non subscribers.

select
subscription_status,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by average_spend,total_revenue desc

#6.which 5 product have the highest percentage of purchases with discounts applied.
 
select
item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS "discount rate"
from customer
group by item_purchased
order by "discount_rate" desc
limit 5;

#-Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as(
    select
    customer_id,
    previous_purchases,
    case 
    when previous_purchases=1 then 'New'
    when previous_purchases between 1 and 10 then 'Returning Customer'
    else 'loyalty'
    end as customer_segment
from customer
)
select 
customer_segment,
count(*) as 'Number of customer'
from customer_type
group by customer_segment

select * from customer;

#top 3 purchased product within each category

with products as (
select
item_purchased,
category,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc ) as itemrank
from customer
group by category,item_purchased)

select 
item_purchased,category,total_orders,itemrank
from products
where itemrank <=3;

#--09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
subscription_status,
count(customer_id) as repeatbuyers
from customer
where previous_purchases>5
group by subscription_status

#what  is the revenue contribution of each age  group

select 
age_group as Age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

import json

notebook_file = "customer_behaviour_analysis_sql.ipynb"
sql_file = "customer_behaviour_analysis.sql"

with open(notebook_file, "r", encoding="utf-8") as f:
    notebook = json.load(f)

sql_queries = []

for cell in notebook["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"]).strip()

        if source.startswith("%%sql"):
            source = source[5:].strip()
            sql_queries.append(source)

        elif source.startswith("%sql"):
            source = source[4:].strip()
            sql_queries.append(source)

with open(sql_file, "w", encoding="utf-8") as f:
    f.write("\n\n".join(sql_queries))

print("SQL file created:", sql_file)